### ISSUE TITLE
Do not create groups again and again

### ISSUE THREAD

**Issue by pcav** [abhijitgujar86/QGIS-Layer-arranger#3]
Once the plugin is run, three groups are created. If I add layers to the project, then re-run the plugin to rearrange the layers, three new groups are created, and so on.
Better leave the three groups, and add newly added layers to the existing groups

**Comment by amsantac** [comment]
It duplicates groups and layers when the plugin is run again

**Comment by abhijitgujar86** [comment]
done. the .2  version is added which reflects the change. thanks for your time .
